server:
  port: 8086
  servlet:
    context-path: /capstore
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstore
    username: root
    password: India123
  jpa:
    generate-ddl: false
    show-sql: true
    
    